--- #YAML:1.0
name:               WWW-Search-PubMedLite
version:            0.04
abstract:           Access PubMed's database of journal articles
author:
    - David J. Iberri <diberri@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::Entities:  0
    Test::More:      0
    WWW::Search:     0
    XML::LibXML:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
