# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Search-PubMedLite
version:      0.02
version_from: lib/WWW/Search/PubMedLite.pm
installdirs:  site
requires:
    HTML::Entities:                0
    Test::More:                    0
    WWW::Search:                   0
    XML::LibXML:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
